
import type { Metadata } from "next";
import "./globals.css";
import HeaderWrapper from "@/components/HeaderWrapper"; 
import ScrollToTop from "@/components/ui/ScrollTotop";

export const metadata: Metadata = {
  title: "Braxtone",
  description: "Generated by Imapro technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ScrollToTop/>
        <HeaderWrapper />
        {children}
      </body>
    </html>
  );
}
